2019-04-23 12:07:01,628 ERROR: Exception on /messages [GET] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 157, in messages
    current_user.add_notification('unread_message_count', 0)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\werkzeug\local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'add_notification'
2019-04-23 12:07:28,499 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:07:40,232 ERROR: Exception on /send_message/john [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 146, in send_message
    user.add_notification('unread_message_count', user.new_messages())
AttributeError: 'User' object has no attribute 'add_notification'
2019-04-23 12:12:07,179 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:12:11,166 ERROR: Exception on /send_message/john [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 145, in send_message
    user.add_notification('unread_message_count', user.new_messages())
AttributeError: 'User' object has no attribute 'add_notification'
2019-04-23 12:12:30,919 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:12:34,164 ERROR: Exception on /send_message/john [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 145, in send_message
    user.add_notification('unread_message_count', user.new_messages())
AttributeError: 'User' object has no attribute 'add_notification'
2019-04-23 12:13:09,145 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:13:12,877 ERROR: Exception on /send_message/john [POST] [in c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\sandra.cabrera\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Sandra.cabrera\microblog\app\main\routes.py", line 145, in send_message
    user.add_notification('unread_message_count', user.new_messages())
AttributeError: 'User' object has no attribute 'add_notification'
2019-04-23 12:16:07,961 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:16:17,177 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:18:31,796 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:20:34,311 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:21:46,110 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:23:12,461 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:36:08,708 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:41:17,743 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:41:30,766 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 12:42:37,821 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:74]
2019-04-23 13:01:14,722 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:78]
2019-04-24 08:01:31,179 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:78]
2019-04-24 08:35:04,103 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:78]
2019-04-24 08:51:05,871 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:78]
2019-04-24 08:53:26,770 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:78]
2019-04-24 08:55:40,448 INFO: Microblog startup [in C:\Users\Sandra.cabrera\microblog\app\__init__.py:78]
